containers-ai/alameda-ai

- .gitignore
- Dockerfile
- docs/PULL_REQUEST_TEMPLATE/default.md
- docs/commit.template
- framework/datastore/file_dao.py
- framework/datastore/influx_dao.py
- framework/datastore/metric_dao.py
- framework/filesystem/fsal.py
- framework/filesystem/fsimpl.py
- framework/filesystem/fsimpl_local.py
- framework/log/logfile_handler.py
- framework/log/logger.py
- framework/utils/sys_utils.py
- requirements.txt
- tests/integration/framework/datastore/test_datastore.py
- tests/unittest/framework/datastore/test_datastore.py
- tests/unittest/framework/filesystem/test_fsimpl_local.py
- tests/unittest/framework/log/test_logger.py
First version framework of AI platform for Alameda project.
> Framework: First version.

- Dockerfile
- requirements.txt
- services/arima/alameda_servicer.py
- services/arima/grpc_server.py
- services/arima/main.py
- services/arima/status.py
- services/arima/workload_prediction.py
- services/arima/workload_prediction/config/granularity_conf.yaml
- services/arima/workload_prediction/config/measurement_conf.yaml
- services/arima/workload_prediction/config/sarimax_config.yaml
- services/arima/workload_prediction/preprocessor.py
- services/arima/workload_prediction/process_threading.py
- services/arima/workload_prediction/recommendation.py
- services/arima/workload_prediction/sarimax_predictor.py
- services/arima/workload_prediction/workload_predictor.py
- services/arima/workload_prediction/workload_utils.py
Provide prototype of workload prediction with arima model.
> feat: workload prediction with arima for demo.

- services/arima/workload_prediction/recommendation.py
- services/arima/workload_prediction/workload_predictor.py
Use temporary mock recommendation result for testing.
> refactor: mock recommendation result.

- framework/datastore/file_dao.py
> fix: Fix grpc policy bug

- services/arima/workload_prediction/recommendation.py
- services/arima/workload_prediction/workload_predictor.py
Add try-catch to handle the error while writing prediction data or
recommendation result via gRPC client (metric_dao).
> refactor: add try-catch while writing result.

- services/arima/recommendation/data_processor.py
- services/arima/recommendation/recommender.py
- services/arima/recommendation/scheduler.py
- skeleton of recommender service, including:
- VPA-stable 
- Scheduler-LoadBalance 
- Data processor.
Issue #12 , #13
> feat: skeleton of recommendation service.

- services/arima/recommendation/config/recommendation_conf.yaml
- services/arima/recommendation/data_processor.py
Query workload data from dao and then transform data into
another structure to meet the requirement for recommendation.
> feat: implement processor for containers workload.

- services/arima/recommendation/data_processor.py
- Query containers predicted workload data in one pod.
- Query pod observed/predicted workload data.
- Query nodes observed/predicted workload data.
> feat: processor for getting different workload.

- services/orchestra/recommendation/init_detector.py
- tests/unittest/services/orchestra/recommendation/test_init_detector.py
Implement the init-stage detector for the container workload
Github issue #12
> feat: init-stage detector

- services/orchestra/recommendation/data_processor.py
Convert container resources from string to numerical value.
> feat: processor for getting container resources.

- services/orchestra/recommendation/config/recommendation_conf.yaml
- services/orchestra/recommendation/stable_scheduler.py
Add concrete implementation of stable scheduler.
Github issue #13
> feat: stable scheduler

- services/orchestra/recommendation/stable_scheduler.py
Modify return values of stable scheduler to include:
1: pod scheduling result
2: score comparison before/after scheduling
3: modified workload prediction of nodes
Github issue #13
> refactor: modify return values of stable scheduler

- services/orchestra/recommendation/data_processor.py
- services/orchestra/recommendation/recommender.py
modify data structure of recommender to meet datahub criterion
Github issue #12
> refactor: recommender with datahub

- services/orchestra/main.py
- services/orchestra/recommendation.py
- services/orchestra/recommendation/data_processor.py
- services/orchestra/recommendation/stable_scheduler.py
- Integrate VPA and scheduler result and then write it to operator.
- Add recommendation entrypoint.
- Modify the way to get pod list in scheduler.
**Github issue** #12 #13
> refactor: integrate VPA and scheduler result.

- README.md
> feat: Add CI badge in README.md

- .coveragerc
- Jenkinsfile
- README.md
Add codecov in jenkinsfile and codecov badge
> feat: Add codecov in jenkinsfile and codecov badge

- framework/datahub/client.py
- services/orchestra/recommendation/data_processor.py
- Fix bug for response status in DatahubClient.
- Fix bug for time_range 'step' data structure in DataProcessor.
> fix: bugs in DatahubClient and DataProcessor.

- Jenkinsfile
> feat: Add pylint to jenkinsfile

- framework/datahub/client.py
- framework/datahub/grpc_mapping.yaml
> refactor: Revise on datahub client

- services/orchestra/recommendation/stable_scheduler.py
Since the order of pods in the input will affect the result of
scheduler, a mechanism to iterate through different order should be
added.
Github issue 13
> Refactor: consider pod order in scheduler.

- services/orchestra/recommendation.py
- services/orchestra/recommendation/data_processor.py
- services/orchestra/recommendation/recommender.py
- services/orchestra/workload_prediction/workload_predictor.py
Fix bugs.
1. Fix request args name while querying node workload in DataProcessor.
2. Sort workload data in ascending order in WorkloadPredictor.
3. Fix process sleep time from 60s to 300s.
Fix recommendation process.
1. Do scheduling only when the pod has new VPA recommendation result.
2. Write VPA result to operator, even if scheduling failed.
3. Write recommendation results to operator via DataProcessor.
> fix: Recommendation process and WorkloadPredictor

- services/orchestra/workload_prediction/sarimax_predictor.py
…elf.log.debug
To ignore unnecessary error message
Github issue #22
> refactor: log.err--> log.debug in grid search of SARIMAXPredictor

- framework/datahub/client.py
- framework/log/logfile_handler.py
- framework/log/logger.py
- tests/unittest/framework/datahub/test_client.py
Add a test for DatahubClient and refine log.
> refactor: Add a test for DatahubClient and refine log.
